name: Haberleri Guncelle

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  guncelle:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # YENİ EKLENEN ADIM: Kazıma kütüphanesini kuruyoruz
      - name: Gerekli Kütüphaneleri Kur
        run: pip install beautifulsoup4

      - name: Botu Çalıştır ve JSON Üret
        run: python bot.py

      - name: Güncel Haberleri GitHub'a Gönder
        run: |
          git config --global user.name "Haber Botu"
          git config --global user.email "bot@habersistemi.com"
          git add haberler.json
          git commit -m "Otomatik güncelleme: Tüm içerikler kazındı" || echo "Yeni haber yok"
          git push
